---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: scr-ser
spec: 
  minReadySeconds: 10
  replicas: 2
  selector: 
    matchLabels:
      app: scr
      ver: "1.0"
  template:
    metadata:
      name: scr-pod
      labels:
        app: scr
        ver: "1.0"
    spec:
      containers:
        - name: scr-app
          image: 
          ports:
            - containerPort: 5000
              protocol: TCP
      imagePullSecrets:
        - name: srinu
         

        
