---
  pool:
    name: devpool
    vmImage: "ubuntu-22.04"
   
  trigger:
    - master
  stages:
    - stage: image
      jobs:
        - job: imagebuild
          steps:
            - script: |
                docker image build -t scr1:2.0 .
                docker image tag scr1:2.0 maheshstar/scr1:2.0
                docker image push maheshstar/scr1:2.0
    - stage: container
      jobs:
        - job: containercreate
          steps:
            - script: |
                docker image ls
                docker image pull maheshstar/scr1:2.0
                docker container run -d -P --name scr1 maheshstar/scr1:2.0
                docker container ls

                            




