---
  pool:
    name: testpool
    vmImage: "ubuntu-22.04"
   
  trigger:
    - master
  
  parameters:
    - name: version
      displayName: version
      type: string
      default: "v1.0"  

    
  steps:
    - task: Docker@2
      inputs:
        command: build
        buildContext: .
        repository: 'StudentsCourses'
        tags: '$(Build.BuildId)'   




