---
apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: src-pvc
spec: 
  accessModes:
    - ReadWriteOnce
  storageClassName: managed-premium
  resources: 
    requests:
      storage: 1Gi    